# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: ory

before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  binary: ory
  env:
    - CGO_ENABLED=0
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
  goos:
    - freebsd
    - linux
#    - plan9
#    - solaris
#    - netbsd
#    - openbsd
    - windows
    - darwin
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
  format_overrides:
  - goos: windows
    format: zip
  files:
    - LICENSE.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: ory
    name: homebrew-ory
  homepage:  https://www.ory.sh
  commit_author:
    name: ory
    email: hi@ory.sh

scoop:
  bucket:
    owner: ory
    name: scoop-ory
  homepage:  https://www.ory.sh
  commit_author:
    name: ory
    email: hi@ory.sh

dockers:
  - image_templates:
    - "oryd/ory:{{ .Tag }}"
    - "oryd/ory:v{{ .Major }}"
    - "oryd/ory:v{{ .Major }}.{{ .Minor }}"
    - "oryd/ory:latest"
