# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  format:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ory/ory
    steps:
      - checkout
      - run:
          name: Enable go1.12 modules
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            source $BASH_ENV
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
      - run: golangci-lint run ./...

  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ory/ory
    steps:
      - run:
          name: Enable go1.12 modules
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            source $BASH_ENV
      - checkout
      - run: go mod download
      - run: go install github.com/mattn/goveralls golang.org/x/tools/cmd/cover github.com/ory/go-acc
      - run: go-acc -o coverage.txt ./... -- -failfast -timeout=20m

  release:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ory/ory
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Enable go1.12 modules
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            source $BASH_ENV
      - run: curl -sL https://git.io/goreleaser | bash
      - run: goreleaser

workflows:
  version: 2
  "test and release":
    jobs:
      - format:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
            - format
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
